version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5435:5433'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./create-db.sql:/docler-entrypoint-initdb.d/create_database.sql